# SentinelVision AI
## Notebook 05B — Supervised Classifier on VideoMAE Embeddings

### Objective

Notebook 03 created VideoMAE embeddings from real surveillance video clips.

Notebook 04 tested unsupervised anomaly detection models on those embeddings.

This notebook tests whether the VideoMAE embeddings can support supervised binary classification:

`normal clip` vs `anomalous-source clip`

The model is not fine-tuning VideoMAE itself.

Instead, VideoMAE stays frozen and we train classifiers on top of the extracted embeddings.

In [1]:
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    roc_auc_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

Load Embeddings

In [2]:
embeddings_path = Path("../data/embeddings/clip_embeddings_videomae_sample.parquet")

embeddings = pd.read_parquet(embeddings_path)

print(embeddings.shape)
embeddings.head()

(600, 775)

,clip_id,video_id,category,binary_label,split,start_seconds,end_seconds,feature_000,feature_001,feature_002,...,feature_758,feature_759,feature_760,feature_761,feature_762,feature_763,feature_764,feature_765,feature_766,feature_767
0,Normal_Videos_365_x264_clip_00003,Normal_Videos_365_x264,Normal,0,test,12.0,16.0,0.178769,3.729066,3.666701,...,2.413040,-1.240642,-1.159237,-1.608377,3.872948,1.565241,0.879731,0.846557,-1.191670,-0.930276
1,Normal_Videos_365_x264_clip_00030,Normal_Videos_365_x264,Normal,0,test,120.0,124.0,0.278189,2.779260,3.542873,...,-0.741295,-1.844295,0.887464,0.550726,3.069808,1.138670,1.094854,0.417987,-1.605511,1.888869
2,Normal_Videos_365_x264_clip_00032,Normal_Videos_365_x264,Normal,0,test,128.0,132.0,0.229807,3.365491,3.970525,...,1.338005,-2.018188,-0.082708,-0.061900,3.764704,1.424313,0.843749,1.016206,-1.329999,1.080641
3,Normal_Videos_641_x264_clip_00015,Normal_Videos_641_x264,Normal,0,test,60.0,64.0,-5.002384,1.898196,0.756616,...,-2.385197,0.084327,4.650817,3.130729,2.914249,-0.534147,2.499364,3.860784,0.763254,-1.158123
4,Normal_Videos_312_x264_clip_00000,Normal_Videos_312_x264,Normal,0,test,0.0,4.0,-4.661326,1.897303,1.866576,...,0.865088,-1.091096,1.328566,4.970067,2.660053,1.487340,2.988191,1.090254,0.692304,0.847159

#### Verify balance

In [3]:
embeddings.groupby(["split", "binary_label"]).size()

split       binary_label
test        0               100
            1               100
train       0               100
            1               100
validation  0               100
            1               100
dtype: int64

In [4]:
feature_columns = [
    column
    for column in embeddings.columns
    if column.startswith("feature_")
]

len(feature_columns)

768

In [5]:
train_data = embeddings[
    embeddings["split"] == "train"
].copy()

validation_data = embeddings[
    embeddings["split"] == "validation"
].copy()

test_data = embeddings[
    embeddings["split"] == "test"
].copy()

print("Train:", train_data.shape)
print("Validation:", validation_data.shape)
print("Test:", test_data.shape)

Train: (200, 775)
Validation: (200, 775)
Test: (200, 775)

In [6]:
features_train = train_data[feature_columns]
target_train = train_data["binary_label"]

features_valid = validation_data[feature_columns]
target_valid = validation_data["binary_label"]

features_test = test_data[feature_columns]
target_test = test_data["binary_label"]

print(features_train.shape)
print(features_valid.shape)
print(features_test.shape)

(200, 768)
(200, 768)
(200, 768)

Helper function for evaluation

In [7]:
def evaluate_classifier(
    model_name,
    model,
    features,
    target,
):
    """
    Evaluate a supervised classifier using predicted probabilities.

    The positive class is 1, meaning anomalous-source clip.
    """
    probabilities = model.predict_proba(features)[:, 1]

    precision, recall, thresholds = precision_recall_curve(
        target,
        probabilities,
    )

    f1_scores = []

    for threshold in thresholds:
        predictions = (
            probabilities >= threshold
        ).astype(int)

        score = f1_score(
            target,
            predictions,
            zero_division=0,
        )

        f1_scores.append(score)

    best_index = int(
        max(
            range(len(f1_scores)),
            key=f1_scores.__getitem__,
        )
    )

    best_threshold = thresholds[best_index]

    predictions = (
        probabilities >= best_threshold
    ).astype(int)

    results = {
        "model": model_name,
        "roc_auc": roc_auc_score(
            target,
            probabilities,
        ),
        "pr_auc": average_precision_score(
            target,
            probabilities,
        ),
        "f1": f1_score(
            target,
            predictions,
            zero_division=0,
        ),
        "threshold": best_threshold,
    }

    print(model_name)
    print(results)
    print()
    print(
        classification_report(
            target,
            predictions,
            zero_division=0,
        )
    )
    print("Confusion matrix:")
    print(
        confusion_matrix(
            target,
            predictions,
        )
    )

    return results

#### Train Logistic Regression

In [8]:
logistic_regression_model = Pipeline(
    steps=[
        (
            "scaler",
            StandardScaler(),
        ),
        (
            "classifier",
            LogisticRegression(
                max_iter=2000,
                class_weight="balanced",
                random_state=42,
            ),
        ),
    ]
)

logistic_regression_model.fit(
    features_train,
    target_train,
)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=2000,
                                    random_state=42))])

In [9]:
logistic_regression_valid_results = evaluate_classifier(
    model_name="Logistic Regression on VideoMAE Embeddings",
    model=logistic_regression_model,
    features=features_valid,
    target=target_valid,
)

logistic_regression_valid_results

Logistic Regression on VideoMAE Embeddings
{'model': 'Logistic Regression on VideoMAE Embeddings', 'roc_auc': 0.9469000000000001, 'pr_auc': 0.952224199361345, 'f1': 0.898989898989899, 'threshold': np.float64(0.9389742904287082)}

              precision    recall  f1-score   support

           0       0.89      0.91      0.90       100
           1       0.91      0.89      0.90       100

    accuracy                           0.90       200
   macro avg       0.90      0.90      0.90       200
weighted avg       0.90      0.90      0.90       200

Confusion matrix:
[[91  9]
 [11 89]]

{'model': 'Logistic Regression on VideoMAE Embeddings',
 'roc_auc': 0.9469000000000001,
 'pr_auc': 0.952224199361345,
 'f1': 0.898989898989899,
 'threshold': np.float64(0.9389742904287082)}

### Train Random Forest

In [16]:
random_forest_model = RandomForestClassifier(
    class_weight="balanced",
    random_state=42
)

random_forest_model.fit(
    features_train,
    target_train,
)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [17]:
random_forest_valid_results = evaluate_classifier(
    model_name="Random Forest on VideoMAE Embeddings",
    model=random_forest_model,
    features=features_valid,
    target=target_valid,
)

random_forest_valid_results

Random Forest on VideoMAE Embeddings
{'model': 'Random Forest on VideoMAE Embeddings', 'roc_auc': 0.9014, 'pr_auc': 0.9204095675648034, 'f1': 0.8374384236453202, 'threshold': np.float64(0.62)}

              precision    recall  f1-score   support

           0       0.85      0.82      0.83       100
           1       0.83      0.85      0.84       100

    accuracy                           0.83       200
   macro avg       0.84      0.83      0.83       200
weighted avg       0.84      0.83      0.83       200

Confusion matrix:
[[82 18]
 [15 85]]

{'model': 'Random Forest on VideoMAE Embeddings',
 'roc_auc': 0.9014,
 'pr_auc': 0.9204095675648034,
 'f1': 0.8374384236453202,
 'threshold': np.float64(0.62)}

#### Train HistGradientBoostingClassifier

In [22]:
hist_gradient_boosting_model = HistGradientBoostingClassifier(
    random_state=42,
)

hist_gradient_boosting_model.fit(
    features_train,
    target_train,
)

HistGradientBoostingClassifier(random_state=42)

In [23]:
hist_gradient_boosting_valid_results = evaluate_classifier(
    model_name="HistGradientBoosting on VideoMAE Embeddings",
    model=hist_gradient_boosting_model,
    features=features_valid,
    target=target_valid,
)

hist_gradient_boosting_valid_results

HistGradientBoosting on VideoMAE Embeddings
{'model': 'HistGradientBoosting on VideoMAE Embeddings', 'roc_auc': 0.9064, 'pr_auc': 0.9262648842080112, 'f1': 0.8350515463917526, 'threshold': np.float64(0.9010280722596212)}

              precision    recall  f1-score   support

           0       0.82      0.87      0.84       100
           1       0.86      0.81      0.84       100

    accuracy                           0.84       200
   macro avg       0.84      0.84      0.84       200
weighted avg       0.84      0.84      0.84       200

Confusion matrix:
[[87 13]
 [19 81]]

{'model': 'HistGradientBoosting on VideoMAE Embeddings',
 'roc_auc': 0.9064,
 'pr_auc': 0.9262648842080112,
 'f1': 0.8350515463917526,
 'threshold': np.float64(0.9010280722596212)}

#### Compare validation results

In [24]:
validation_results = pd.DataFrame(
    [
        logistic_regression_valid_results,
        random_forest_valid_results,
        hist_gradient_boosting_valid_results,
    ]
)

validation_results.sort_values(
    by="pr_auc",
    ascending=False,
)

,model,roc_auc,pr_auc,f1,threshold
0,Logistic Regression on VideoMAE Embeddings,0.9469,0.952224,0.898990,0.938974
2,HistGradientBoosting on VideoMAE Embeddings,0.9064,0.926265,0.835052,0.901028
1,Random Forest on VideoMAE Embeddings,0.9014,0.920410,0.837438,0.620000

#### best validation model

In [25]:
best_validation_result = validation_results.sort_values(
    by="pr_auc",
    ascending=False,
).iloc[0]

best_validation_result

model        Logistic Regression on VideoMAE Embeddings
roc_auc                                          0.9469
pr_auc                                         0.952224
f1                                              0.89899
threshold                                      0.938974
Name: 0, dtype: object

In [26]:
trained_models = {
    "Logistic Regression on VideoMAE Embeddings": logistic_regression_model,
    "Random Forest on VideoMAE Embeddings": random_forest_model,
    "HistGradientBoosting on VideoMAE Embeddings": hist_gradient_boosting_model,
}

best_model_name = best_validation_result["model"]

best_model = trained_models[
    best_model_name
]

best_model_name

'Logistic Regression on VideoMAE Embeddings'

#### Use the validation threshold from the best model

In [27]:
best_threshold = best_validation_result["threshold"]

best_threshold

np.float64(0.9389742904287082)

Evaluate the best model on the test set

In [28]:
test_probabilities = best_model.predict_proba(
    features_test
)[:, 1]

test_predictions = (
    test_probabilities >= best_threshold
).astype(int)

In [29]:
supervised_test_results = {
    "model": best_model_name,
    "roc_auc": roc_auc_score(
        target_test,
        test_probabilities,
    ),
    "pr_auc": average_precision_score(
        target_test,
        test_probabilities,
    ),
    "f1": f1_score(
        target_test,
        test_predictions,
        zero_division=0,
    ),
    "threshold": best_threshold,
}

supervised_test_results

{'model': 'Logistic Regression on VideoMAE Embeddings',
 'roc_auc': 0.9020999999999999,
 'pr_auc': 0.877501454769589,
 'f1': 0.8282828282828283,
 'threshold': np.float64(0.9389742904287082)}

#### Classification report

In [30]:
print(
    classification_report(
        target_test,
        test_predictions,
        zero_division=0,
    )
)

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       100
           1       0.84      0.82      0.83       100

    accuracy                           0.83       200
   macro avg       0.83      0.83      0.83       200
weighted avg       0.83      0.83      0.83       200

In [31]:
confusion_matrix(
    target_test,
    test_predictions,
)

array([[84, 16],
       [18, 82]])

In [32]:
metrics_dir = Path("../artifacts/metrics")
models_dir = Path("../models/production")

metrics_dir.mkdir(
    parents=True,
    exist_ok=True,
)

models_dir.mkdir(
    parents=True,
    exist_ok=True,
)

In [33]:
supervised_results = pd.DataFrame(
    [supervised_test_results]
)

supervised_results.to_csv(
    metrics_dir / "supervised_videomae_results.csv",
    index=False,
)

joblib.dump(
    best_model,
    models_dir / "supervised_videomae_classifier.joblib",
)

supervised_results

,model,roc_auc,pr_auc,f1,threshold
0,Logistic Regression on VideoMAE Embeddings,0.9021,0.877501,0.828283,0.938974

#### Compare against Notebook 04

In [34]:
baseline_results = pd.read_csv(
    metrics_dir / "baseline_model_results.csv"
)

combined_results = pd.concat(
    [
        baseline_results,
        supervised_results,
    ],
    ignore_index=True,
)

combined_results.sort_values(
    by="pr_auc",
    ascending=False,
)

,model,roc_auc,pr_auc,f1,threshold
2,Logistic Regression on VideoMAE Embeddings,0.9021,0.877501,0.828283,0.938974
0,Distance Threshold Baseline,0.6950,0.774326,0.628975,NaN
1,Isolation Forest,0.6659,0.732748,0.636364,NaN